services:
  postgresDB:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=user_mydb
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mydb
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5436:5432"